version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
      
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:c3631a7f-fa25-43d5-9489-69e66286c978@git.heroku.com/webinar-demo-kat.git master
